### PR TITLE
Support pydantic 2

### PR DESCRIPTION
**Pull request by trungleduc**
close https://github.com/QuantStack/jupytercad/issues/209

### CODE REVIEW

**Comment by martinRenou** [comment]
CI failures are unrelated, right? Let's merge and fix it separately?

**Review by martinRenou — APPROVED** [review]
LGTM!

**Comment by trungleduc** [comment]
> CI failures are unrelated, right? Let's merge and fix it separately?

I'm not sure, let me check before merging.

**Comment by trungleduc** [comment]
It looks better now, let's merge it and fix the UI test later.

**Review by martinRenou — APPROVED** [review]

**Comment by martinRenou** [comment]
Well, turns out I have no right on the repo since the move! I cannot merge

**Comment by trungleduc** [comment]
> Well, turns out I have no right on the repo since the move! I cannot merge

Done

**Comment by martinRenou** [comment]
Are you able to give me rights on the repo?

**Comment by trungleduc** [comment]
> Are you able to give me rights on the repo?

yes, i did

**Pull request merged**
